default: &default
  adapter: postgresql
  user: uheyiamhere
  password: 123456789
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: heyiamheredb

test:
  <<: *default
  database: heyiamheredb

production:
  <<: *default
  database: heyiamheredb
